### ISSUE TITLE
No DTS tracks found

### ISSUE THREAD

**Issue by exxogene** [dcthomson/mkvdts2ac3.py#12]
Dear dcthomson,

i like your great script and it works for me for some time.

But now it do not find any DTS inside the mkv files anymore. When i use the -vvv switch it says "No DTS tracks found". This happens regardless of the mkv files i try to convert, even with the test files provided by you.

I run the script on Win7 x64 with Python 2.7.8 and ffmpeg-20140711-git-0089fb7-win32 and mkvtoolnix-amd64-7.0.0. 

Here are the options i use in the mkvdts2ac3.cfg:

aac = True
# aacstereo = True

default = True
# external = True

force = True
initial = True
# keepdts = True
# mp4 = True

new = False
nodts = True
# no_subtitles = True

overwrite = True
recursive = True
# test = True

debug = True

I haven't edited the mkvdts2ac3.py. I've put python, mkvtoolnix and ffmpeg in the windows path variable.

Maybe i have messed something. Do you have any idea what is broken in my setup?

Thank you.
/exxo

**Comment by matthewchubb** [comment]
> Small parameter error on issue #11
> en_US is not supported as a parameter, in stead use "en". Using "list" will return all available languages.
> You didn't get this exception?
> 
> ```
> Traceback (most recent call last):
>   File "mkvdts2ac3.py", line 650, in process
>     output = subprocess.check_output([mkvinfo, "--ui-language", "en_US", ford])
> ```
> 
> After adjusting this it works like a charm with mkvtoolnix 7.0

Works for me now, thank you everybody!

Any idea how I would get this working on a synology (currently got it working in windows test env). On my synology I run all of my automation including radarr and nzbget both in docker containers although i could install NZBget nativly if required, I couldn't find a way to install mkvtoolbox other than in a docker container also and as such I don't know how to find its path to enter in to the script variables.. 

Currently i get the following error;

When I try to do this I get the following error in my nzbget log which seem to suggest its the paths i need to work on?


Fri Oct 16 00:00:12 2020 INFO Executing post-process-script mkvdts2ac3.py for [MOVIE_TILE]

Fri Oct 16 00:00:12 2020 INFO mkvdts2ac3: File "/downloads/scripts/mkvdts2ac3.py", line 418

Fri Oct 16 00:00:12 2020 INFO mkvdts2ac3: print "\nYou can use --mkvtoolnixpath and --ffmpegpath to specify the path"

Fri Oct 16 00:00:12 2020 INFO mkvdts2ac3: ^

Fri Oct 16 00:00:12 2020 INFO mkvdts2ac3: SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nYou can use --mkvtoolnixpath and --ffmpegpath to specify the path")?

Fri Oct 16 00:00:12 2020 ERROR Post-process-script mkvdts2ac3.py for [MOVIE_TILE] failed (terminated with unknown status)

Fri Oct 16 00:00:12 2020 INFO Collection [MOVIE_TILE] added to history

Fri Oct 16 00:00:33 2020 INFO Deleting [MOVIE_TILE] from history

Fri Oct 16 00:00:33 2020 INFO Deleting file /downloads/nzb/[MOVIE_TILE].nzb.queued

Fri Oct 16 00:00:33 2020 INFO Collection [MOVIE_TILE] removed from history

Please help!

Thanks.
